[project]
name = "music-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=3.0.3",
    "pillow",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.2",
    "spotipy>=2.26.0",
    "streamlit>=1.57.0",
]
