import psycopg
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from typing import Callable, Optional
from zoneinfo import ZoneInfo

TZ_AMSTERDAM = ZoneInfo("Europe/Amsterdam")

# Playlist helpers for music-tracker.
#
# SAFETY CONTRACT: modification calls (playlist_replace_items, playlist_add_items)
# are ONLY ever made on the playlist id returned by find_or_create_managed_playlist.
# The following spotipy methods are explicitly forbidden in this module and must
# never be added: playlist_remove_all_occurrences_of_items,
# playlist_remove_specific_occurrences_of_items, user_playlist_remove_*,
# current_user_unfollow_playlist.

UPDATING_NAME_SUFFIX = " · Auto 🤖🔄"
SNAPSHOT_NAME_SUFFIX = " · Auto 🤖📸"

AUTO_PLAYLIST_DESCRIPTION_UPDATING = (
    "Auto-generated by music-tracker. Manual edits will be overwritten on the next refresh."
)
AUTO_PLAYLIST_DESCRIPTION_SNAPSHOT = (
    "Auto-generated snapshot by music-tracker. This playlist is frozen and will not be updated."
)


# ── Dataclass ─────────────────────────────────────────────────────────────────

@dataclass
class PlaylistDefinition:
    """A definition for one managed auto-playlist."""
    suffix: str                                          # e.g. "100+ plays" → full name "100+ plays · Auto 🤖🔄"
    description: str                                     # per-playlist tagline
    query_fn: Callable[[psycopg.Connection], list[str]]  # returns list of track_uris in desired order
    kind: str = "updating"                               # "updating" or "snapshot"
    max_tracks: int = 10000                              # safety cap (Spotify max is 10000 per playlist)
    legacy_names: list[str] = field(default_factory=list)  # chain of past names, tried in order


# ── Name/description helpers ───────────────────────────────────────────────────

def get_full_name(definition: PlaylistDefinition) -> str:
    """Build the full Spotify playlist name from a definition."""
    suffix = SNAPSHOT_NAME_SUFFIX if definition.kind == "snapshot" else UPDATING_NAME_SUFFIX
    return f"{definition.suffix}{suffix}"


def get_full_description(definition: PlaylistDefinition) -> str:
    """Build the full Spotify playlist description from a definition."""
    boilerplate = (
        AUTO_PLAYLIST_DESCRIPTION_SNAPSHOT if definition.kind == "snapshot"
        else AUTO_PLAYLIST_DESCRIPTION_UPDATING
    )
    return f"{definition.description} {boilerplate}"


# ── Query helpers ─────────────────────────────────────────────────────────────

def query_plays_threshold_at_least(min_plays: int, limit: int = 10000):
    """Tracks with at least min_plays plays, ordered by plays DESC."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY track_uri
            HAVING COUNT(*) >= %s
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (min_plays, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_plays_threshold_band(min_plays: int, max_plays: int, limit: int = 10000):
    """Tracks with plays in [min_plays, max_plays], ordered by plays DESC."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY track_uri
            HAVING COUNT(*) BETWEEN %s AND %s
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (min_plays, max_plays, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_recent(days: int, limit: int):
    """Top tracks by plays in the last `days` days."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND played_at >= NOW() - (INTERVAL '1 day' * %s)
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (days, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_current_year(limit: int):
    """Top tracks by plays in current local year (Europe/Amsterdam)."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND EXTRACT(YEAR FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int =
                  EXTRACT(YEAR FROM (NOW() AT TIME ZONE 'Europe/Amsterdam'))::int
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (limit,),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_all_time(limit: int):
    """Top tracks all-time."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (limit,),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_in_month(year: int, month: int, limit: int):
    """Top tracks by plays in a specific (year, month) — Europe/Amsterdam timezone."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND EXTRACT(YEAR FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int = %s
              AND EXTRACT(MONTH FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int = %s
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (year, month, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_in_date_range(start_date_local: date, end_date_local_inclusive: date, limit: int):
    """Top tracks in a date range (inclusive), interpreted in Europe/Amsterdam."""
    start_dt = datetime.combine(start_date_local, datetime.min.time(), TZ_AMSTERDAM)
    end_dt = datetime.combine(
        end_date_local_inclusive + timedelta(days=1),
        datetime.min.time(),
        TZ_AMSTERDAM,
    )

    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND played_at >= %s
              AND played_at < %s
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (start_dt, end_dt, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_in_year(year: int, limit: int):
    """Top tracks by plays in a specific year — Europe/Amsterdam timezone."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND EXTRACT(YEAR FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int = %s
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (year, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_through_year_end(year: int, limit: int):
    """All-time top tracks considering only plays through Dec 31 of given year."""
    end_dt = datetime(year + 1, 1, 1, 0, 0, 0, tzinfo=TZ_AMSTERDAM)

    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND played_at < %s
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (end_dt, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


# ── Query helpers (dynamic) ───────────────────────────────────────────────────

def query_year_released_tracks(release_bucket: str):
    """Returns a query function for liked tracks in the given release bucket.

    release_bucket is either 'Pre-2013' (all tracks with release_year < 2013) or a
    year string like '2024' (tracks with release_year = that year).
    """
    def fn(conn):
        cur = conn.cursor()
        if release_bucket == "Pre-2013":
            cur.execute(
                """
                SELECT ls.track_uri
                FROM liked_songs ls
                INNER JOIN track_metadata tm ON tm.track_uri = ls.track_uri
                WHERE tm.release_year IS NOT NULL
                  AND tm.release_year < 2013
                ORDER BY tm.release_date ASC NULLS LAST, ls.liked_at ASC
                """
            )
        else:
            cur.execute(
                """
                SELECT ls.track_uri
                FROM liked_songs ls
                INNER JOIN track_metadata tm ON tm.track_uri = ls.track_uri
                WHERE tm.release_year = %s
                ORDER BY tm.release_date ASC NULLS LAST, ls.liked_at ASC
                """,
                (int(release_bucket),),
            )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_year_discovered_tracks(discovered_year: str):
    """Returns a query function for liked tracks first discovered in the given year (or 'Undefined').

    'Discovered' = first play in spotify_plays for that track.
    'Undefined' = first played within 30 days of data start (can't tell if discovered then or earlier).
    """
    def fn(conn):
        cur = conn.cursor()
        if discovered_year == "Undefined":
            cur.execute(
                """
                WITH first_plays AS (
                    SELECT track_uri, MIN(played_at) AS first_played_at
                    FROM spotify_plays
                    WHERE track_uri IS NOT NULL
                    GROUP BY track_uri
                ),
                data_start AS (
                    SELECT MIN(played_at) + INTERVAL '30 days' AS cutoff FROM spotify_plays
                )
                SELECT fp.track_uri
                FROM first_plays fp
                INNER JOIN liked_songs ls ON ls.track_uri = fp.track_uri
                CROSS JOIN data_start ds
                WHERE fp.first_played_at < ds.cutoff
                ORDER BY fp.first_played_at ASC
                """
            )
        else:
            cur.execute(
                """
                WITH first_plays AS (
                    SELECT track_uri, MIN(played_at) AS first_played_at
                    FROM spotify_plays
                    WHERE track_uri IS NOT NULL
                    GROUP BY track_uri
                ),
                data_start AS (
                    SELECT MIN(played_at) + INTERVAL '30 days' AS cutoff FROM spotify_plays
                )
                SELECT fp.track_uri
                FROM first_plays fp
                INNER JOIN liked_songs ls ON ls.track_uri = fp.track_uri
                CROSS JOIN data_start ds
                WHERE fp.first_played_at >= ds.cutoff
                  AND EXTRACT(YEAR FROM fp.first_played_at AT TIME ZONE 'Europe/Amsterdam')::text = %s
                ORDER BY fp.first_played_at ASC
                """,
                (discovered_year,),
            )
        return [row[0] for row in cur.fetchall()]
    return fn


# ── Registry ──────────────────────────────────────────────────────────────────

STATIC_PLAYLISTS: list[PlaylistDefinition] = [
    PlaylistDefinition(
        suffix="20-49 plays",
        description="Tracks you've heard 20-49 times — the 'still figuring out' tier.",
        query_fn=query_plays_threshold_band(20, 49),
        kind="updating",
        legacy_names=["🤖 Auto · 20-49 plays"],
    ),
    PlaylistDefinition(
        suffix="50+ plays",
        description="Tracks you've heard at least 50 times.",
        query_fn=query_plays_threshold_at_least(50),
        kind="updating",
        legacy_names=["🤖 Auto · 50+ plays", "[test] music-tracker — 50+ plays"],
    ),
    PlaylistDefinition(
        suffix="100+ plays",
        description="Tracks you've heard at least 100 times.",
        query_fn=query_plays_threshold_at_least(100),
        kind="updating",
        legacy_names=["🤖 Auto · 100+ plays"],
    ),
    PlaylistDefinition(
        suffix="200+ plays",
        description="Tracks you've heard at least 200 times.",
        query_fn=query_plays_threshold_at_least(200),
        kind="updating",
        legacy_names=["🤖 Auto · 200+ plays"],
    ),
    PlaylistDefinition(
        suffix="300+ plays",
        description="Tracks you've heard at least 300 times.",
        query_fn=query_plays_threshold_at_least(300),
        kind="updating",
        legacy_names=["🤖 Auto · 300+ plays"],
    ),
    PlaylistDefinition(
        suffix="400+ plays",
        description="Tracks you've heard at least 400 times.",
        query_fn=query_plays_threshold_at_least(400),
        kind="updating",
        legacy_names=["🤖 Auto · 400+ plays"],
    ),
    PlaylistDefinition(
        suffix="500+ plays",
        description="Tracks you've heard at least 500 times — your obsessions.",
        query_fn=query_plays_threshold_at_least(500),
        kind="updating",
        legacy_names=["🤖 Auto · 500+ plays"],
    ),
    PlaylistDefinition(
        suffix="Top 50 last 30 days",
        description="Your 50 most-played tracks in the past 30 days.",
        query_fn=query_top_recent(days=30, limit=50),
        kind="updating",
        legacy_names=["🤖 Auto · Top 50 last 30 days"],
    ),
    PlaylistDefinition(
        suffix="Top 100 this year",
        description="Your 100 most-played tracks in the current calendar year.",
        query_fn=query_top_current_year(limit=100),
        kind="updating",
        legacy_names=["🤖 Auto · Top 100 this year"],
    ),
    PlaylistDefinition(
        suffix="Top 100 all-time",
        description="Your 100 most-played tracks across all time.",
        query_fn=query_top_all_time(limit=100),
        kind="updating",
        legacy_names=["🤖 Auto · Top 100 all-time"],
    ),
]


def year_discovered_playlists(conn) -> list[PlaylistDefinition]:
    """Generate one PlaylistDefinition per discovery year for liked songs.

    Returns 'Undefined' first (for tracks already in library at data start), then years ascending.
    """
    cur = conn.cursor()
    cur.execute(
        """
        WITH first_plays AS (
            SELECT track_uri, MIN(played_at) AS first_played_at
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY track_uri
        ),
        data_start AS (
            SELECT MIN(played_at) + INTERVAL '30 days' AS cutoff FROM spotify_plays
        ),
        liked_first_plays AS (
            SELECT fp.track_uri, fp.first_played_at, ds.cutoff
            FROM first_plays fp
            INNER JOIN liked_songs ls ON ls.track_uri = fp.track_uri
            CROSS JOIN data_start ds
        ),
        classified AS (
            SELECT
                CASE
                    WHEN first_played_at < cutoff THEN 'Undefined'
                    ELSE EXTRACT(YEAR FROM first_played_at AT TIME ZONE 'Europe/Amsterdam')::text
                END AS discovered_year
            FROM liked_first_plays
        )
        SELECT discovered_year, COUNT(*) AS cnt
        FROM classified
        GROUP BY discovered_year
        HAVING COUNT(*) > 0
        ORDER BY
            CASE WHEN discovered_year = 'Undefined' THEN 0 ELSE 1 END,
            discovered_year
        """
    )
    rows = cur.fetchall()

    definitions = []
    for discovered_year, _count in rows:
        suffix = f"{discovered_year} · Discovered"
        if discovered_year == "Undefined":
            description = (
                "Liked tracks already in your library when data collection started "
                "(Feb 2017) — exact discovery year unknown."
            )
        else:
            description = (
                f"Liked tracks you discovered in {discovered_year} — first heard that year, "
                "ordered by first-play date."
            )

        definitions.append(
            PlaylistDefinition(
                suffix=suffix,
                description=description,
                query_fn=query_year_discovered_tracks(discovered_year),
                kind="updating",
            )
        )

    return definitions


def year_released_playlists(conn) -> list[PlaylistDefinition]:
    """Generate one PlaylistDefinition per release-year bucket for liked songs.

    Years < 2013 collapse into a single 'Pre-2013' bucket. Years >= 2013 get per-year
    playlists. Excludes future-dated tracks (release_year > current year). Skips empty
    buckets (HAVING > 0). Returns newest year first, then 'Pre-2013' at the end.
    """
    cur = conn.cursor()
    cur.execute(
        """
        WITH classified AS (
            SELECT
                CASE
                    WHEN tm.release_year < 2013 THEN 'Pre-2013'
                    ELSE tm.release_year::text
                END AS release_bucket
            FROM liked_songs ls
            INNER JOIN track_metadata tm ON tm.track_uri = ls.track_uri
            WHERE tm.release_year IS NOT NULL
              AND tm.release_year <= EXTRACT(YEAR FROM NOW())::int
        )
        SELECT release_bucket, COUNT(*) AS cnt
        FROM classified
        GROUP BY release_bucket
        HAVING COUNT(*) > 0
        ORDER BY
            CASE WHEN release_bucket = 'Pre-2013' THEN 1 ELSE 0 END,
            release_bucket DESC
        """
    )
    rows = cur.fetchall()

    definitions = []
    for release_bucket, _count in rows:
        suffix = f"{release_bucket} · Released"
        if release_bucket == "Pre-2013":
            description = (
                "Liked tracks released before 2013, ordered by release date."
            )
        else:
            description = (
                f"Liked tracks released in {release_bucket}, ordered by release date within the year."
            )
        definitions.append(
            PlaylistDefinition(
                suffix=suffix,
                description=description,
                query_fn=query_year_released_tracks(release_bucket),
                kind="updating",
            )
        )

    return definitions


def monthly_top_snapshots(conn) -> list[PlaylistDefinition]:
    """One snapshot per COMPLETED month with plays. Skips current month."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT
            EXTRACT(YEAR FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int AS yr,
            EXTRACT(MONTH FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int AS mo
        FROM spotify_plays
        WHERE track_uri IS NOT NULL
        GROUP BY yr, mo
        HAVING COUNT(*) > 0
        ORDER BY yr DESC, mo DESC
        """
    )
    rows = cur.fetchall()

    now_local = datetime.now(TZ_AMSTERDAM)
    current_year, current_month = now_local.year, now_local.month

    MONTH_NAMES = [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ]

    definitions = []
    for yr, mo in rows:
        if (yr, mo) >= (current_year, current_month):
            continue
        month_name = MONTH_NAMES[mo - 1]
        suffix = f"Top 25 · {month_name} {yr}"
        description = f"Your 25 most-played tracks in {month_name} {yr}."
        definitions.append(
            PlaylistDefinition(
                suffix=suffix,
                description=description,
                query_fn=query_top_in_month(yr, mo, limit=25),
                kind="snapshot",
                max_tracks=25,
            )
        )
    return definitions


def seasonal_top_snapshots(conn) -> list[PlaylistDefinition]:
    """One snapshot per COMPLETED astronomical season fully covered by our data.

    NL astronomical seasons:
      Winter: Dec 21 (year N-1) – Mar 20 (year N), NAMED BY END YEAR.
      Spring: Mar 21 – Jun 20, named by year.
      Summer: Jun 21 – Sep 22, named by year.
      Autumn: Sep 23 – Dec 20, named by year.
    """
    cur = conn.cursor()
    cur.execute(
        """
        SELECT MIN(played_at AT TIME ZONE 'Europe/Amsterdam')::date AS data_start,
               MAX(played_at AT TIME ZONE 'Europe/Amsterdam')::date AS data_end
        FROM spotify_plays
        """
    )
    data_start, _data_end = cur.fetchone()

    now_local = datetime.now(TZ_AMSTERDAM).date()

    # (name, start_month, start_day, end_month, end_day, winter_end_year_offset)
    SEASONS = [
        ("Winter", 12, 21, 3, 20, True),    # spans year boundary
        ("Spring", 3, 21, 6, 20, False),
        ("Summer", 6, 21, 9, 22, False),
        ("Autumn", 9, 23, 12, 20, False),
    ]

    definitions = []

    for year in range(data_start.year, now_local.year + 1):
        for name, sm, sd, em, ed, wraps_year in SEASONS:
            if wraps_year:
                # Winter "year N" = Dec 21 of (N-1) to Mar 20 of N
                start = date(year - 1, sm, sd)
                end = date(year, em, ed)
            else:
                start = date(year, sm, sd)
                end = date(year, em, ed)

            # Must be fully completed (end <= today)
            if end > now_local:
                continue
            # Must be fully within data range (start >= data_start)
            if start < data_start:
                continue

            suffix = f"Top 50 · {name} {year}"
            description = f"Your 50 most-played tracks during {name} {year}."
            definitions.append(
                PlaylistDefinition(
                    suffix=suffix,
                    description=description,
                    query_fn=query_top_in_date_range(start, end, limit=50),
                    kind="snapshot",
                    max_tracks=50,
                )
            )

    # Sort newest first
    definitions.sort(key=lambda d: d.suffix, reverse=True)
    return definitions


def yearly_top_snapshots(conn) -> list[PlaylistDefinition]:
    """One Top 100 snapshot per COMPLETED year. Includes partial first year."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT EXTRACT(YEAR FROM MIN(played_at) AT TIME ZONE 'Europe/Amsterdam')::int
        FROM spotify_plays
        """
    )
    first_year = cur.fetchone()[0]

    current_year = datetime.now(TZ_AMSTERDAM).year

    definitions = []
    for year in range(current_year - 1, first_year - 1, -1):  # newest first
        suffix = f"Top 100 · {year}"
        description = f"Your 100 most-played tracks in {year}."
        definitions.append(
            PlaylistDefinition(
                suffix=suffix,
                description=description,
                query_fn=query_top_in_year(year, limit=100),
                kind="snapshot",
                max_tracks=100,
            )
        )
    return definitions


def all_time_top_yearly_snapshots(conn) -> list[PlaylistDefinition]:
    """One all-time Top 100 snapshot per COMPLETED year-end.

    'Top 100 · All-Time · 2018' = top 100 considering only plays through Dec 31, 2018.
    """
    cur = conn.cursor()
    cur.execute(
        """
        SELECT EXTRACT(YEAR FROM MIN(played_at) AT TIME ZONE 'Europe/Amsterdam')::int
        FROM spotify_plays
        """
    )
    first_year = cur.fetchone()[0]

    current_year = datetime.now(TZ_AMSTERDAM).year

    definitions = []
    for year in range(current_year - 1, first_year - 1, -1):  # newest first
        suffix = f"Top 100 · All-Time · {year}"
        description = f"Your 100 most-played tracks all-time as of end of {year}."
        definitions.append(
            PlaylistDefinition(
                suffix=suffix,
                description=description,
                query_fn=query_top_through_year_end(year, limit=100),
                kind="snapshot",
                max_tracks=100,
            )
        )
    return definitions


_MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

_MONTHLY_NUMBER_ONE_DESCRIPTION = (
    "Auto-managed by music-tracker. Manual edits will be overwritten on refresh."
)


def _monthly_top_one_per_month(conn) -> list[tuple[int, int, str]]:
    """One row per (year, month) with the top track URI, ordered yr ASC, mo ASC.

    Tie-breaking: on equal plays, earliest first_play_at wins (deterministic).
    """
    cur = conn.cursor()
    cur.execute(
        """
        WITH per_month AS (
            SELECT
                EXTRACT(YEAR  FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int AS yr,
                EXTRACT(MONTH FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int AS mo,
                track_uri,
                COUNT(*) AS plays,
                MIN(played_at) AS first_play_at
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY yr, mo, track_uri
        ),
        ranked AS (
            SELECT yr, mo, track_uri, plays, first_play_at,
                   ROW_NUMBER() OVER (
                       PARTITION BY yr, mo
                       ORDER BY plays DESC, first_play_at ASC
                   ) AS rn
            FROM per_month
        )
        SELECT yr, mo, track_uri
        FROM ranked
        WHERE rn = 1
        ORDER BY yr DESC, mo DESC
        """
    )
    return cur.fetchall()


def month_number_one_playlists(conn) -> list[PlaylistDefinition]:
    """12 PlaylistDefinitions — one per calendar month, each holding that month's #1
    track across all years, ordered by year ASC.
    """
    rows = _monthly_top_one_per_month(conn)

    def make_query_fn(uris):
        def fn(_conn):
            return uris
        return fn

    definitions = []
    for mo_num in range(1, 13):
        month_name = _MONTH_NAMES[mo_num - 1]
        month_uris = [uri for yr, mo, uri in rows if mo == mo_num]
        definitions.append(
            PlaylistDefinition(
                suffix=f"My {month_name} #1",
                description=_MONTHLY_NUMBER_ONE_DESCRIPTION,
                query_fn=make_query_fn(month_uris),
                kind="updating",
            )
        )

    return definitions


def rolling_monthly_number_one_playlist(conn) -> list[PlaylistDefinition]:
    """One PlaylistDefinition — one track per (year, month) the user had plays in,
    ordered oldest-first. Grows by one entry each month.
    """
    rows = _monthly_top_one_per_month(conn)
    all_uris = [uri for _yr, _mo, uri in rows]

    def query_fn(_conn):
        return all_uris

    return [
        PlaylistDefinition(
            suffix="My Monthly #1",
            description=_MONTHLY_NUMBER_ONE_DESCRIPTION,
            query_fn=query_fn,
            kind="updating",
        )
    ]


def get_managed_playlists(conn) -> list[PlaylistDefinition]:
    """Return all managed playlist definitions (static + dynamic)."""
    dynamic = []
    dynamic.extend(year_discovered_playlists(conn))
    dynamic.extend(year_released_playlists(conn))
    dynamic.extend(monthly_top_snapshots(conn))
    dynamic.extend(seasonal_top_snapshots(conn))
    dynamic.extend(yearly_top_snapshots(conn))
    dynamic.extend(all_time_top_yearly_snapshots(conn))
    dynamic.extend(month_number_one_playlists(conn))
    dynamic.extend(rolling_monthly_number_one_playlist(conn))
    return STATIC_PLAYLISTS + dynamic


# ── Core playlist management ───────────────────────────────────────────────────

def _ensure_playlist_metadata(sp, playlist_id: str, name: str, description: str):
    """Idempotent: set name + description (description already fully built by caller)."""
    sp.playlist_change_details(
        playlist_id,
        name=name,
        description=description,
    )


def find_or_create_managed_playlist(
    sp,
    user_id: str,
    definition: PlaylistDefinition,
    playlist_cache: dict[str, str] | None = None,
) -> tuple[str, bool]:
    """Find an existing playlist by name (or legacy_names), or create it.

    Returns (playlist_id, was_created). was_created is True only when this call
    created the playlist; False if it was found by name or legacy_name.

    If playlist_cache is provided (dict mapping name -> playlist_id), use it as
    the source of truth instead of paginating the user's playlists. The cache
    is built once per script run and avoids redundant API calls.
    """
    full_name = get_full_name(definition)
    full_description = get_full_description(definition)

    if playlist_cache is not None:
        # Cache path
        playlist_id = playlist_cache.get(full_name)
        if playlist_id:
            print(f"[playlists] Cache hit for '{full_name}'.", flush=True)
            _ensure_playlist_metadata(sp, playlist_id, full_name, full_description)
            return (playlist_id, False)

        for legacy_name in definition.legacy_names:
            legacy_id = playlist_cache.get(legacy_name)
            if legacy_id:
                print(f"[playlists] Cache hit for legacy '{legacy_name}'. Renaming...", flush=True)
                _ensure_playlist_metadata(sp, legacy_id, full_name, full_description)
                print(f"[playlists] Renamed to '{full_name}'.", flush=True)
                return (legacy_id, False)

        print(f"[playlists] Cache miss — creating '{full_name}'.", flush=True)
        new = sp.user_playlist_create(
            user=user_id,
            name=full_name,
            public=True,
            description=full_description,
        )
        _ensure_playlist_metadata(sp, new["id"], full_name, full_description)
        playlist_cache[full_name] = new["id"]
        print(f"[playlists] Created '{full_name}'.", flush=True)
        return (new["id"], True)

    # Legacy path: paginate user's playlists
    print(f"[playlists] Searching for '{full_name}'...", flush=True)
    offset = 0
    current_id = None
    legacy_id = None
    legacy_matched_name = None
    n = 0
    while True:
        page = sp.current_user_playlists(limit=50, offset=offset)
        items = page["items"]
        print(f"[playlists]   page {n}: {len(items)} playlists fetched", flush=True)
        for pl in items:
            if pl["owner"]["id"] != user_id:
                continue
            if pl["name"] == full_name:
                current_id = pl["id"]
                break
            if legacy_id is None:
                for legacy_name in definition.legacy_names:
                    if pl["name"] == legacy_name:
                        legacy_id = pl["id"]
                        legacy_matched_name = legacy_name
                        break
        if current_id or page["next"] is None:
            break
        offset += 50
        n += 1

    if current_id:
        print(f"[playlists] Found '{full_name}'. Refreshing metadata...", flush=True)
        _ensure_playlist_metadata(sp, current_id, full_name, full_description)
        return (current_id, False)

    if legacy_id:
        print(f"[playlists] Found legacy '{legacy_matched_name}'. Renaming...", flush=True)
        _ensure_playlist_metadata(sp, legacy_id, full_name, full_description)
        print(f"[playlists] Renamed to '{full_name}'.", flush=True)
        return (legacy_id, False)

    print(f"[playlists] Not found. Creating '{full_name}'...", flush=True)
    new = sp.user_playlist_create(
        user=user_id,
        name=full_name,
        public=True,
        description=full_description,
    )
    _ensure_playlist_metadata(sp, new["id"], full_name, full_description)
    print(f"[playlists] Created '{full_name}'.", flush=True)
    return (new["id"], True)


def update_managed_playlist(
    sp,
    conn,
    user_id: str,
    definition: PlaylistDefinition,
    playlist_cache: dict[str, str] | None = None,
) -> dict:
    """Refresh one managed playlist: find/create, run query, replace tracks.
    Returns {'name': str, 'playlist_id': str, 'track_count': int, 'action': str}."""
    full_name = get_full_name(definition)
    playlist_id, was_created = find_or_create_managed_playlist(
        sp, user_id, definition, playlist_cache
    )

    if definition.kind == "snapshot" and not was_created:
        return {
            "name": full_name,
            "playlist_id": playlist_id,
            "track_count": 0,
            "action": "skipped (snapshot exists)",
        }

    track_uris = definition.query_fn(conn)[: definition.max_tracks]
    replace_playlist_tracks(sp, playlist_id, track_uris)

    return {
        "name": full_name,
        "playlist_id": playlist_id,
        "track_count": len(track_uris),
        "action": "created" if was_created else "updated",
    }


def replace_playlist_tracks(sp, playlist_id: str, uris: list[str]) -> None:
    """Replace the playlist's tracks with the given URIs."""
    print(f"[playlists] Replacing playlist contents with {len(uris)} tracks...", flush=True)
    if not uris:
        sp.playlist_replace_items(playlist_id, [])
        print("[playlists] Replace complete.", flush=True)
        return

    sp.playlist_replace_items(playlist_id, uris[:100])
    for i in range(100, len(uris), 100):
        batch = uris[i : i + 100]
        print(f"[playlists]   Adding batch of {len(batch)} tracks...", flush=True)
        sp.playlist_add_items(playlist_id, batch)
        print("[playlists]   Batch added.", flush=True)
    print("[playlists] Replace complete.", flush=True)
