import psycopg
from dataclasses import dataclass, field
from typing import Callable, Optional

# Playlist helpers for music-tracker.
#
# SAFETY CONTRACT: modification calls (playlist_replace_items, playlist_add_items)
# are ONLY ever made on the playlist id returned by find_or_create_managed_playlist.
# The following spotipy methods are explicitly forbidden in this module and must
# never be added: playlist_remove_all_occurrences_of_items,
# playlist_remove_specific_occurrences_of_items, user_playlist_remove_*,
# current_user_unfollow_playlist.

AUTO_PLAYLIST_PREFIX = "🤖 Auto · "
AUTO_PLAYLIST_DESCRIPTION = (
    "Auto-generated by music-tracker. Manual edits will be overwritten on the next refresh."
)


# ── Dataclass ─────────────────────────────────────────────────────────────────

@dataclass
class PlaylistDefinition:
    """A definition for one managed auto-playlist."""
    suffix: str                                          # e.g. "100+ plays" → full name "🤖 Auto · 100+ plays"
    description: str                                     # per-playlist tagline; combined with AUTO_PLAYLIST_DESCRIPTION
    query_fn: Callable[[psycopg.Connection], list[str]]  # returns list of track_uris in desired order
    max_tracks: int = 10000                              # safety cap (Spotify max is 10000 per playlist)
    legacy_name: Optional[str] = None                   # if set, also search for this name and rename it


# ── Query helpers ─────────────────────────────────────────────────────────────

def query_plays_threshold_at_least(min_plays: int, limit: int = 10000):
    """Tracks with at least min_plays plays, ordered by plays DESC."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY track_uri
            HAVING COUNT(*) >= %s
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (min_plays, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_plays_threshold_band(min_plays: int, max_plays: int, limit: int = 10000):
    """Tracks with plays in [min_plays, max_plays], ordered by plays DESC."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY track_uri
            HAVING COUNT(*) BETWEEN %s AND %s
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (min_plays, max_plays, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_recent(days: int, limit: int):
    """Top tracks by plays in the last `days` days."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND played_at >= NOW() - (INTERVAL '1 day' * %s)
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (days, limit),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_current_year(limit: int):
    """Top tracks by plays in current local year (Europe/Amsterdam)."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
              AND EXTRACT(YEAR FROM played_at AT TIME ZONE 'Europe/Amsterdam')::int =
                  EXTRACT(YEAR FROM (NOW() AT TIME ZONE 'Europe/Amsterdam'))::int
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (limit,),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


def query_top_all_time(limit: int):
    """Top tracks all-time."""
    def fn(conn):
        cur = conn.cursor()
        cur.execute(
            """
            SELECT track_uri
            FROM spotify_plays
            WHERE track_uri IS NOT NULL
            GROUP BY track_uri
            ORDER BY COUNT(*) DESC
            LIMIT %s
            """,
            (limit,),
        )
        return [row[0] for row in cur.fetchall()]
    return fn


# ── Registry ──────────────────────────────────────────────────────────────────

MANAGED_PLAYLISTS: list[PlaylistDefinition] = [
    PlaylistDefinition(
        suffix="20-49 plays",
        description="Tracks you've heard 20-49 times — the 'still figuring out' tier.",
        query_fn=query_plays_threshold_band(20, 49),
    ),
    PlaylistDefinition(
        suffix="50+ plays",
        description="Tracks you've heard at least 50 times.",
        query_fn=query_plays_threshold_at_least(50),
        legacy_name="[test] music-tracker — 50+ plays",  # for safety; should already be renamed
    ),
    PlaylistDefinition(
        suffix="100+ plays",
        description="Tracks you've heard at least 100 times.",
        query_fn=query_plays_threshold_at_least(100),
    ),
    PlaylistDefinition(
        suffix="200+ plays",
        description="Tracks you've heard at least 200 times.",
        query_fn=query_plays_threshold_at_least(200),
    ),
    PlaylistDefinition(
        suffix="300+ plays",
        description="Tracks you've heard at least 300 times.",
        query_fn=query_plays_threshold_at_least(300),
    ),
    PlaylistDefinition(
        suffix="400+ plays",
        description="Tracks you've heard at least 400 times.",
        query_fn=query_plays_threshold_at_least(400),
    ),
    PlaylistDefinition(
        suffix="500+ plays",
        description="Tracks you've heard at least 500 times — your obsessions.",
        query_fn=query_plays_threshold_at_least(500),
    ),
    PlaylistDefinition(
        suffix="Top 50 last 30 days",
        description="Your 50 most-played tracks in the past 30 days.",
        query_fn=query_top_recent(days=30, limit=50),
    ),
    PlaylistDefinition(
        suffix="Top 100 this year",
        description="Your 100 most-played tracks in the current calendar year.",
        query_fn=query_top_current_year(limit=100),
    ),
    PlaylistDefinition(
        suffix="Top 100 all-time",
        description="Your 100 most-played tracks across all time.",
        query_fn=query_top_all_time(limit=100),
    ),
]


# ── Core playlist management ───────────────────────────────────────────────────

def _ensure_playlist_metadata(sp, playlist_id: str, name: str, description: str):
    """Idempotent: set name + description."""
    full_description = f"{description} {AUTO_PLAYLIST_DESCRIPTION}"
    sp.playlist_change_details(
        playlist_id,
        name=name,
        description=full_description,
    )


def find_or_create_managed_playlist(sp, user_id: str, definition: PlaylistDefinition) -> str:
    """Find an existing playlist matching the definition's full name, falling back to legacy_name,
    or create it. Returns the playlist ID. Applies metadata (name + description) idempotently."""
    full_name = AUTO_PLAYLIST_PREFIX + definition.suffix

    print(f"[playlists] Searching for '{full_name}'...", flush=True)
    offset = 0
    current_id = None
    legacy_id = None
    n = 0
    while True:
        page = sp.current_user_playlists(limit=50, offset=offset)
        items = page["items"]
        print(f"[playlists]   page {n}: {len(items)} playlists fetched", flush=True)
        for pl in items:
            if pl["owner"]["id"] != user_id:
                continue
            if pl["name"] == full_name:
                current_id = pl["id"]
                break
            if definition.legacy_name and pl["name"] == definition.legacy_name:
                legacy_id = pl["id"]
        if current_id or page["next"] is None:
            break
        offset += 50
        n += 1

    if current_id:
        print(f"[playlists] Found '{full_name}'. Refreshing metadata...", flush=True)
        _ensure_playlist_metadata(sp, current_id, full_name, definition.description)
        return current_id

    if legacy_id:
        print(f"[playlists] Found legacy '{definition.legacy_name}'. Renaming...", flush=True)
        _ensure_playlist_metadata(sp, legacy_id, full_name, definition.description)
        print(f"[playlists] Renamed to '{full_name}'.", flush=True)
        return legacy_id

    print(f"[playlists] Not found. Creating '{full_name}'...", flush=True)
    full_description = f"{definition.description} {AUTO_PLAYLIST_DESCRIPTION}"
    new = sp.user_playlist_create(
        user=user_id,
        name=full_name,
        public=True,
        description=full_description,
    )
    _ensure_playlist_metadata(sp, new["id"], full_name, definition.description)
    print(f"[playlists] Created '{full_name}'.", flush=True)
    return new["id"]


def update_managed_playlist(sp, conn, user_id: str, definition: PlaylistDefinition) -> dict:
    """Refresh one managed playlist: find/create, run query, replace tracks.
    Returns {'name': str, 'playlist_id': str, 'track_count': int, 'action': 'created'|'updated'}."""
    full_name = AUTO_PLAYLIST_PREFIX + definition.suffix
    playlist_id = find_or_create_managed_playlist(sp, user_id, definition)
    track_uris = definition.query_fn(conn)[:definition.max_tracks]
    spotify_uris = [f"spotify:track:{uri}" if not uri.startswith("spotify:") else uri
                    for uri in track_uris]
    replace_playlist_tracks(sp, playlist_id, spotify_uris)
    return {
        "name": full_name,
        "playlist_id": playlist_id,
        "track_count": len(spotify_uris),
        "action": "updated",
    }


def replace_playlist_tracks(sp, playlist_id: str, uris: list[str]) -> None:
    """Replace the playlist's tracks with the given URIs."""
    print(f"[playlists] Replacing playlist contents with {len(uris)} tracks...", flush=True)
    if not uris:
        sp.playlist_replace_items(playlist_id, [])
        print("[playlists] Replace complete.", flush=True)
        return

    sp.playlist_replace_items(playlist_id, uris[:100])
    for i in range(100, len(uris), 100):
        batch = uris[i : i + 100]
        print(f"[playlists]   Adding batch of {len(batch)} tracks...", flush=True)
        sp.playlist_add_items(playlist_id, batch)
        print("[playlists]   Batch added.", flush=True)
    print("[playlists] Replace complete.", flush=True)
